name: Close stale PRs

on:
  schedule:
    - cron: '*/5 * * * *' # runs every 5 minutes

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR is stale because it has been open for 5 minutes with no activity. Closing.'
          close-pr-message: 'Closing this stale PR. Feel free to reopen if you are still working on it.'
          stale-pr-label: 'stale'
          days-before-stale: 0 # immediately mark PRs as stale
          days-before-close: 0 # immediately close stale PRs
          operations-per-run: 500 # maximum number of operations per run
          remove-stale-when-updated: true # remove stale label when PR is updated